### ISSUE TITLE
 Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by nicheProgramming** [hydrabolt/discord.js-guide#2]
Following the development and setup process up to the first bot had brought this error message
`class Client extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/discord.js/src/index.js:2:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

should the example code include the use of strict to conteract this, or am I simply doing something wrong?

**Comment by RunEMC** [comment]
Had the same problem, solved by updating node to the latest version.

**Comment by Buttars** [comment]
While using meteor, updating node isn't an option. Is there any fixes to this issue?

**Comment by vecchiotom** [comment]
i had the same issue, solved by downgrading node to 6.11.1
